arc_monitoring_servers docs
Azure/arc_jumpstart_docs pull request #305
Opened 2024-05-08 16:37 UTC by alsanch

arc_monitoring_servers docs

2024-05-09 06:51 UTC, janegilring approved these changes
Looks very good, added some minor suggestions on wording and casing.

2024-05-09 06:51 UTC, janegilring commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +Infrastructure observability is crucial for Contoso Motors to understand the performance and health of their Azure Arc-enabled servers. This is where [Azure Monitor](https://learn.microsoft.com/azure
```suggestion
Infrastructure observability is crucial for Contoso Motors to understand the performance and health of their Azure Arc-enabled servers. This is where [Azure Monitor](https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/hybrid/arc-enabled-servers/eslz-management-and-monitoring-arc-server) steps in, playing a vital role in offering visibility into every facet of their Azure Arc-enabled servers ecosystem.
```

2024-05-09 06:51 UTC, janegilring commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +## Azure Arc-enabled servers and Azure Monitor VMInsights Integration
We should use the same casing as https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-overview

```suggestion
## Azure Arc-enabled servers and Azure Monitor VM insights Integration
```

2024-05-09 06:51 UTC, janegilring commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +Now that we have checked that the required monitoring artifacts have been successfully enabled, it's time to leverage VMInsights. It monitors the performance of your Azure Arc-enabled servers by coll
We should use the same casing as https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-overview
```suggestion
Now that we have checked that the required monitoring artifacts have been successfully enabled, it's time to leverage VM insights. It monitors the performance of your Azure Arc-enabled servers by collecting the required data with AMA.
```

2024-05-09 06:51 UTC, janegilring commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +    ![Screenshot of VMInsights - Performance](./img/vminsights_performance.png)
We should use the same casing as https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-overview
```suggestion
    ![Screenshot of VM insights - Performance](./img/vminsights_performance.png)
```

2024-05-09 06:51 UTC, janegilring commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +An Azure Monitor Workbook for Operating System (OS) Performance is also available as part of the deployment. It complements the views provided by VMInsights.
We should use the same casing as https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-overview
```suggestion
An Azure Monitor Workbook for Operating System (OS) Performance is also available as part of the deployment. It complements the views provided by VM insights.
```

2024-05-10 11:31 UTC, fcabrera23 commented
@alsanch could you please rebase this branch based on the latest canary branch? I've added the configurations to get the Vale linitn check

2024-05-15 17:35 UTC, sebassem requested changes
LGTM
@alsanch 
Very minor changes

2024-05-15 17:35 UTC, sebassem commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +Azure Monitor can collect data directly from your Arc-enabled servers into a Log Analytics workspace for detailed analysis and correlation. It requires installing the Azure Monitor Agent (AMA) VM ext
```suggestion
Azure Monitor can collect data directly from your Arc-enabled servers into a Log Analytics workspace for detailed analysis and correlation. It requires installing the Azure Monitor Agent (AMA) VM extension on your Azure Arc-enabled servers, enabling VM insights to collect data from your machines.
```

2024-05-15 17:35 UTC, sebassem commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +An Azure Monitor Workbook for Operating System (OS) Performance is also available as part of the deployment. It complements the views provided by VM insights.
```suggestion
An Azure Workbook for Operating System (OS) Performance is also available as part of the deployment. It complements the views provided by VM insights.
```
I think they are called Azure Workbooks now

2024-05-15 17:35 UTC, sebassem commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +- The second and third inventories list your **Azure Arc-enabled servers** and your **Azure Arc-enabled Kubernetes clusters**. It provides information about the status, the Arc agent version, the Ope
```suggestion
- The second and third inventories list your **Azure Arc-enabled servers** and your **Azure Arc-enabled Kubernetes clusters**. It provides information about the status, Arc agent version, the operating system, location, and the number of compliant and non-compliant policies.
```

2024-05-16 06:22 UTC, alsanch commented on docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
> +  ![Screenshot of inventory workbook arc servers and kubernetes clusters](./img/defenderalerts_inventoryworkbook.png)
Completed
![image](https://github.com/Azure/arc_jumpstart_docs/assets/96136892/a8fb6d38-92ae-4ac9-a5c4-5ebe635ccea9)

2024-05-16 06:26 UTC, merged