Resolving issue #2566
Azure/arc_jumpstart_docs pull request #423
Opened 2024-10-15 14:19 UTC by ldabas-msft

This PR addresses #2566

2024-10-16 13:54 UTC, janegilring requested changes

2024-10-16 13:54 UTC, janegilring commented on docs/azure_jumpstart_hcibox/cloud_deployment/_index.md
> +> If you are having difficulties connecting into a stack HCI vm:
"Stack HCI VM"

2024-10-28 23:42 UTC, ldabas-msft commented on docs/azure_jumpstart_hcibox/cloud_deployment/_index.md
> +> If you are having difficulties connecting into a stack HCI vm:
updated

2024-10-29 16:14 UTC, fcabrera23 approved these changes
LGTM

2024-10-29 16:15 UTC, merged